version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: pnpm start:dev
    ports:
      - 3000:3000
  
  prod-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    env_file:
      - .env
    ports:
      - 3001:3000

  postgres:
    image: postgres:13.16
    env_file: .env
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  redis:
    image: redis:7.4.1-alpine
    env_file: .env
    entrypoint: redis-server --appendonly yes  --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
